# Generated by Django 2.2.2 on 2021-03-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=128)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=32, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=128)),
                ('txn_type', models.CharField(choices=[('WalletTopUp', 'WalletTopUp'), ('Checkout', 'Checkout')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('failed', 'failed'), ('success', 'success')], default='pending', max_length=32)),
                ('txn_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(max_length=128)),
                ('user_id', models.CharField(max_length=128)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
