# Generated by Django 2.2.2 on 2021-03-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='mpesa_receipt',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
