# Generated by Django 2.2.2 on 2021-03-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210305_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='account',
            field=models.CharField(default='', max_length=128),
        ),
    ]
