# Generated by Django 2.2.2 on 2021-03-11 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210305_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpesatransaction',
            options={'ordering': ('-txn_date',)},
        ),
    ]
