# Generated by Django 2.2.2 on 2021-03-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210311_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='user_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
