# Generated by Django 2.2.2 on 2021-03-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mpesatransaction_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('txn_id', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('account', models.CharField(max_length=128)),
                ('txn_type', models.CharField(default='CheckoutFromWallet', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('failed', 'failed'), ('success', 'success')], default='pending', max_length=32)),
                ('txn_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-txn_date',),
            },
        ),
    ]
