# Generated by Django 2.2.2 on 2021-03-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_wallettransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2CWithdrawalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=32)),
                ('txn_id', models.CharField(max_length=256)),
                ('txn_ref', models.CharField(blank=True, max_length=128, null=True)),
                ('amount', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=128, null=True)),
                ('remarks', models.CharField(default='Wallet Withdrawal', max_length=140)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
