# Generated by Django 2.2.2 on 2021-03-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_b2cwithdrawalrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpesatransaction',
            options={'ordering': ('txn_date',)},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ('txn_date',)},
        ),
    ]
