# Generated by Django 2.2.2 on 2021-04-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_coupon_applies_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='percent_off',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
