# Generated by Django 2.2.2 on 2021-04-04 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210404_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='applies_to',
        ),
    ]
