# Generated by Django 2.2.2 on 2021-04-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210404_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
