# Generated by Django 2.2.2 on 2021-04-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210405_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='created',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_redemptions',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='redeem_by',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='times_redeemed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
